// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/account/index.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/users/[login].tsx";
import * as $6 from "./routes/welcome.tsx";
import * as $$0 from "./islands/UserNav.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/account/index.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/users/[login].tsx": $5,
    "./routes/welcome.tsx": $6,
  },
  islands: {
    "./islands/UserNav.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
