// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/account/index.tsx";
import * as $4 from "./routes/api/items/[id].ts";
import * as $5 from "./routes/api/items/index.ts";
import * as $6 from "./routes/api/users/[login]/index.ts";
import * as $7 from "./routes/api/users/[login]/items.ts";
import * as $8 from "./routes/api/users/index.ts";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/users/[login].tsx";
import * as $11 from "./routes/welcome.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/account/index.tsx": $3,
    "./routes/api/items/[id].ts": $4,
    "./routes/api/items/index.ts": $5,
    "./routes/api/users/[login]/index.ts": $6,
    "./routes/api/users/[login]/items.ts": $7,
    "./routes/api/users/index.ts": $8,
    "./routes/index.tsx": $9,
    "./routes/users/[login].tsx": $10,
    "./routes/welcome.tsx": $11,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
