// from https://github.com/hyoban/unocss-preset-shadcn
import type {
  Preset,
  VariantContext,
  VariantObject,
} from "../../../deps/@unocss/core.ts";
import {
  h,
  variantGetParameter,
  type Theme,
} from "../../../deps/@unocss/preset-mini.ts";
import { generateCSSVars } from "./generate.ts";
import { PresetShadcnOptions } from "./types.ts";

// WORKAROUND: `bg-opacity-90` instead of `bg-primary/90`, `bg-opacity-80`
// instead of `bg-secondary/80` and `bg-opacity/90` instead of `bg-destructive/90`

const variantGroupDataAttribute: VariantObject = {
  name: "group-data",
  match(matcher, ctx: VariantContext<Theme>) {
    const variant = variantGetParameter(
      "group-data-",
      matcher,
      ctx.generator.config.separators,
    );
    if (variant) {
      const [match, rest] = variant;
      const dataAttribute = h.bracket(match) ?? ctx.theme.data?.[match] ?? "";
      if (dataAttribute) {
        return {
          matcher: `group-[[data-${dataAttribute}]]:${rest}`,
        };
      }
    }
  },
};

const generateColorClasses = (): string[] => {
  const colors = [
    "gray",
    "red",
    "yellow",
    "green",
    "blue",
    "indigo",
    "purple",
    "pink",
  ];
  const variants = ["text", "bg"];
  const increments = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  const classNames: string[] = [];

  colors.forEach((color) => {
    variants.forEach((variant) => {
      increments.forEach((increment) => {
        classNames.push(`${variant}-${color}-${increment}`);
      });
    });
  });

  return classNames;
};

export function presetShadcn(options: PresetShadcnOptions = {}): Preset<Theme> {
  // IMPORTANT: note that functions are dropped for CSR mode due to by
  // esbuild serialization so we use non-function syntax where possible
  return {
    name: "unocss-preset-shadcn",

    preflights: [
      {
        getCSS: () => `
          @keyframes shadcn-down { from{ height: 0 } to { height: var(--radix-accordion-content-height)} }
          @keyframes shadcn-up { from{ height: var(--radix-accordion-content-height)} to { height: 0 } }
          @keyframes shadcn-collapsible-down { from{ height: 0 } to { height: var(--radix-collapsible-content-height)} }
          @keyframes shadcn-collapsible-up { from{ height: var(--radix-collapsible-content-height)} to { height: 0 } }

          ${generateCSSVars(options)}

          * {
            border-color: hsl(var(--border));
          }

          body {
            color: hsl(var(--foreground));
            background: hsl(var(--background));
          }
        `,
      },
    ],

    // WORKAROUND: force include dynamically injected classes (e.g. when opening dialog)
    // for shadcn-ui components which dynamically mount/unmount with additional classes.
    // This allows disabling CSR mode which significantly slows-down hydration due primarily
    // to the presetIcons() preset (which injects the larger MDI collection) used by presetShadcn().
    // see https://github.com/netzo/netzo/issues/172
    // GPT PROMPT: "List all unique classNames in an array[] format fot the tsx file: <FILE>"
    safelist: [
      ...new Set([
        // colors:
        ...generateColorClasses(),
        // icons:
        ...[
          "mdi-checkbox-blank-outline",
          "mdi-checkbox-marked",
          "mdi-magnify",
          "mdi-arrow-up",
          "mdi-arrow-down",
          "mdi-arrow-left",
          "mdi-arrow-right",
          "mdi-chevron-up",
          "mdi-chevron-down",
          "mdi-chevron-left",
          "mdi-chevron-right",
          "mdi-close",
          "mdi-check",
          "mdi-menu",
          "mdi-dots-vertical",
          "mdi-dots-horizontal",
        ],
        // accordion:
        ...[
          "border-b",
          "flex",
          "flex-1",
          "items-center",
          "justify-between",
          "py-4",
          "bg-inherit",
          "text-sm",
          "font-medium",
          "transition-all",
          "hover:underline",
          "[&[data-state=open]>svg]:rotate-180",
          "mdi-chevron-down",
          "h-4",
          "w-4",
          "shrink-0",
          "text-muted-foreground",
          "transition-transform",
          "duration-200",
          "overflow-hidden",
          "data-[state=closed]:animate-accordion-up",
          "data-[state=open]:animate-accordion-down",
          "pb-4",
          "pt-0",
        ],
        // alert-dialog:
        ...[
          "fixed",
          "inset-0",
          "z-50",
          "bg-black/80",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "grid",
          "w-full",
          "max-w-lg",
          "translate-x-[-50%]",
          "translate-y-[-50%]",
          "gap-4",
          "border",
          "bg-background",
          "p-6",
          "shadow-lg",
          "duration-200",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[state=closed]:slide-out-to-left-1/2",
          "data-[state=closed]:slide-out-to-top-[48%]",
          "data-[state=open]:slide-in-from-left-1/2",
          "data-[state=open]:slide-in-from-top-[48%]",
          "sm:rounded-lg",
          "flex",
          "flex-col",
          "space-y-2",
          "text-center",
          "sm:text-left",
          "flex-col-reverse",
          "sm:flex-row",
          "sm:justify-end",
          "sm:space-x-2",
          "text-lg",
          "font-semibold",
          "text-sm",
          "text-muted-foreground",
          "mt-2",
          "sm:mt-0",
        ],
        // badge:
        ...[
          "inline-flex",
          "items-center",
          "rounded-md",
          "border",
          "px-2.5",
          "py-0.5",
          "text-xs",
          "font-semibold",
          "transition-colors",
          "focus:outline-none",
          "focus:ring-2",
          "focus:ring-ring",
          "focus:ring-offset-2",
          "default",
          "border-transparent",
          "bg-primary",
          "text-primary-foreground",
          "bg-secondary",
          "text-secondary-foreground",
          "shadow",
          "hover:bg-opacity-80",
        ],
        // carousel:
        ...[
          "relative",
          "overflow-hidden",
          "flex",
          "-ml-4",
          "-mt-4",
          "flex-col",
          "min-w-0",
          "shrink-0",
          "grow-0",
          "basis-full",
          "pl-4",
          "pt-4",
          "absolute",
          "h-8",
          "w-8",
          "rounded-full",
          "-left-12",
          "top-1/2",
          "-translate-y-1/2",
          "-top-12",
          "-translate-x-1/2",
          "rotate-90",
          "-right-12",
          "-bottom-12",
          "mdi-arrow-left",
          "mdi-arrow-right",
          "sr-only",
        ],
        // combobox:
        ...[
          "w-full",
          "justify-between",
          "hover:bg-secondary/20",
          "active:scale-100",
          "line-clamp-1",
          "text-left",
          "font-normal",
          "mr-2",
          "mdi-chevron-down",
          "ml-2",
          "h-4",
          "w-4",
          "shrink-0",
          "rotate-0",
          "opacity-50",
          "transition-transform",
          "rotate-180",
          "p-0",
          "max-h-60",
          "mdi-check",
          "opacity-0",
          "opacity-100",
        ],
        // context-menu:
        ...[
          "flex",
          "cursor-default",
          "select-none",
          "items-center",
          "rounded-sm",
          "px-2",
          "py-1.5",
          "text-sm",
          "outline-none",
          "focus:bg-accent",
          "focus:text-accent-foreground",
          "bg-transparent",
          "data-[state=open]:bg-accent",
          "data-[state=open]:text-accent-foreground",
          "pl-8",
          "mdi-chevron-right",
          "ml-auto",
          "h-4",
          "w-4",
          "shrink-0",
          "rotate-0",
          "opacity-50",
          "transition-transform",
          "rotate-180",
          "z-50",
          "min-w-[8rem]",
          "overflow-hidden",
          "border",
          "bg-popover",
          "p-1",
          "text-popover-foreground",
          "shadow-lg",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
          "max-h-60",
          "data-[disabled]:pointer-events-none",
          "data-[disabled]:opacity-50",
          "fill-current",
          "mdi-circle-medium",
          "-mx-1",
          "my-1",
          "h-px",
          "bg-border",
          "text-foreground",
          "font-semibold",
          "text-muted-foreground",
          "text-xs",
          "tracking-widest",
        ],
        // dialog:
        ...[
          "fixed",
          "inset-0",
          "z-50",
          "bg-black/80",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "left-[50%]",
          "top-[50%]",
          "grid",
          "w-full",
          "max-w-lg",
          "translate-x-[-50%]",
          "translate-y-[-50%]",
          "gap-4",
          "border",
          "bg-background",
          "p-6",
          "shadow-lg",
          "duration-200",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[state=closed]:slide-out-to-left-1/2",
          "data-[state=closed]:slide-out-to-top-[48%]",
          "data-[state=open]:slide-in-from-left-1/2",
          "data-[state=open]:slide-in-from-top-[48%]",
          "sm:rounded-lg",
          "space-y-1.5",
          "text-center",
          "sm:text-left",
          "flex-col",
          "flex-col-reverse",
          "sm:flex-row",
          "sm:justify-end",
          "sm:space-x-2",
          "text-lg",
          "font-semibold",
          "leading-none",
          "tracking-tight",
          "text-sm",
          "text-muted-foreground",
          "rounded-sm",
          "opacity-70",
          "ring-offset-background",
          "transition-opacity",
          "hover:opacity-100",
          "focus:outline-none",
          "focus:ring-2",
          "focus:ring-ring",
          "focus:ring-offset-2",
          "disabled:pointer-events-none",
          "bg-transparent",
          "data-[state=open]:bg-accent",
          "data-[state=open]:text-muted-foreground",
        ],
        // drawer:
        ...[
          "fixed",
          "inset-0",
          "z-50",
          "bg-black/80",
          "inset-x-0",
          "bottom-0",
          "mt-24",
          "flex",
          "h-auto",
          "flex-col",
          "rounded-t-[10px]",
          "border",
          "bg-background",
          "mx-auto",
          "mt-4",
          "h-2",
          "w-[100px]",
          "rounded-full",
          "bg-muted",
          "grid",
          "gap-1.5",
          "p-4",
          "text-center",
          "sm:text-left",
          "mt-auto",
          "gap-2",
          "text-lg",
          "font-semibold",
          "leading-none",
          "tracking-tight",
          "text-sm",
          "text-muted-foreground",
        ],
        // dropdown-menu:
        ...[
          "flex",
          "cursor-default",
          "select-none",
          "items-center",
          "rounded-sm",
          "px-2",
          "py-1.5",
          "text-sm",
          "outline-none",
          "focus:bg-accent",
          "bg-transparent",
          "data-[state=open]:bg-accent",
          "pl-8",
          "ml-auto",
          "h-4",
          "w-4",
          "z-50",
          "min-w-[8rem]",
          "overflow-hidden",
          "border",
          "bg-popover",
          "p-1",
          "text-popover-foreground",
          "shadow-lg",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
          "mdi-chevron-right",
          "mdi-check",
          "fill-current",
          "absolute",
          "left-2",
          "h-3.5",
          "w-3.5",
          "justify-center",
          "data-[disabled]:pointer-events-none",
          "data-[disabled]:opacity-50",
          "data-[state=closed]:animate-out",
          "data-[state=open]:animate-in",
          "data-[state=open]:zoom-in-95",
          "data-[state=closed]:zoom-out-95",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "-mx-1",
          "my-1",
          "h-px",
          "bg-muted",
          "text-xs",
          "tracking-widest",
          "opacity-60",
        ],
        // hover-card:
        ...[
          "z-50",
          "w-64",
          "rounded-md",
          "border",
          "bg-popover",
          "p-4",
          "text-popover-foreground",
          "shadow-md",
          "outline-none",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
        ],
        // menubar:
        ...[
          "flex",
          "h-9",
          "items-center",
          "space-x-1",
          "rounded-md",
          "border",
          "bg-background",
          "p-1",
          "shadow-sm",
          "cursor-default",
          "select-none",
          "px-3",
          "py-1",
          "text-sm",
          "font-medium",
          "outline-none",
          "focus:bg-accent",
          "focus:text-accent-foreground",
          "bg-transparent",
          "data-[state=open]:bg-accent",
          "data-[state=open]:text-accent-foreground",
          "z-50",
          "min-w-[12rem]",
          "overflow-hidden",
          "bg-popover",
          "shadow-md",
          "data-[state=open]:animate-in",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
          "ml-auto",
          "text-xs",
          "tracking-widest",
          "text-muted-foreground",
          "-mx-1",
          "my-1",
          "h-px",
          "bg-muted",
        ],
        // navigation-menu:
        ...[
          "relative",
          "z-10",
          "flex",
          "max-w-max",
          "flex-1",
          "items-center",
          "justify-center",
          "group",
          "list-none",
          "space-x-1",
          "h-9",
          "w-max",
          "rounded-md",
          "bg-background",
          "px-4",
          "py-2",
          "text-sm",
          "font-medium",
          "transition-colors",
          "hover:bg-accent",
          "hover:text-accent-foreground",
          "focus:bg-accent",
          "focus:text-accent-foreground",
          "focus:outline-none",
          "disabled:pointer-events-none",
          "disabled:opacity-50",
          "data-[active]:bg-accent/50",
          "bg-transparent",
          "data-[state=open]:bg-accent/50",
          "left-0",
          "top-0",
          "w-full",
          "data-[motion^=from-]:animate-in",
          "data-[motion^=to-]:animate-out",
          "data-[motion^=from-]:fade-in",
          "data-[motion^=to-]:fade-out",
          "data-[motion=from-end]:slide-in-from-right-52",
          "data-[motion=from-start]:slide-in-from-left-52",
          "data-[motion=to-end]:slide-out-to-right-52",
          "data-[motion=to-start]:slide-out-to-left-52",
          "md:absolute",
          "md:w-auto",
          "origin-top-center",
          "mt-1.5",
          "h-[var(--radix-navigation-menu-viewport-height)]",
          "w-full",
          "overflow-hidden",
          "border",
          "bg-popover",
          "text-popover-foreground",
          "shadow",
          "md:w-[var(--radix-navigation-menu-viewport-width)]",
          "absolute",
          "left-0",
          "top-full",
          "justify-center",
          "z-[1]",
          "h-1.5",
          "overflow-hidden",
          "data-[state=visible]:animate-in",
          "data-[state=hidden]:animate-out",
          "data-[state=hidden]:fade-out",
          "data-[state=visible]:fade-in",
          "rotate-45",
          "rounded-tl-sm",
          "bg-border",
          "shadow-md",
        ],
        // popover:
        ...[
          "z-50",
          "w-72",
          "rounded-md",
          "border",
          "bg-popover",
          "p-4",
          "text-popover-foreground",
          "shadow-md",
          "outline-none",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "data-[state=closed]:zoom-out-95",
          "data-[state=open]:zoom-in-95",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
        ],
        // select:
        ...[
          "flex",
          "h-9",
          "w-full",
          "items-center",
          "justify-between",
          "whitespace-nowrap",
          "rounded-md",
          "border",
          "border-input",
          "bg-transparent",
          "px-3",
          "py-2",
          "text-sm",
          "shadow-sm",
          "ring-offset-background",
          "placeholder:text-muted-foreground",
          "focus:outline-none",
          "focus:ring-1",
          "focus:ring-ring",
          "disabled:cursor-not-allowed",
          "disabled:opacity-50",
          "[&>span]:line-clamp-1",
          "h-4",
          "w-4",
          "opacity-50",
          "relative",
          "right-2",
          "py-1",
          "-mx-1",
          "my-1",
          "h-px",
          "bg-muted",
        ],
        // select-multiple:
        ...[
          "w-full",
          "justify-between",
          "h-full",
          "h-10",
          "flex",
          "gap-1",
          "flex-wrap",
          "mr-1",
          "mb-1",
          "ml-1",
          "ring-offset-background",
          "rounded-full",
          "outline-none",
          "focus:ring-2",
          "focus:ring-ring",
          "focus:ring-offset-2",
          "shrink-0",
          "opacity-50",
          "max-h-64",
          "overflow-auto",
        ],
        // separator:
        "shrink-0",
        "bg-border",
        "h-[1px]",
        "w-full",
        "h-full",
        "w-[1px]",
        // sheet:
        ...[
          "fixed",
          "inset-0",
          "z-50",
          "bg-black/80",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=open]:fade-in-0",
          "gap-4",
          "bg-background",
          "p-6",
          "shadow-lg",
          "transition",
          "ease-in-out",
          "data-[state=closed]:duration-300",
          "data-[state=open]:duration-500",
          "border-b",
          "border-t",
          "border-r",
          "border-l",
          "inset-x-0",
          "top-0",
          "bottom-0",
          "left-0",
          "h-full",
          "w-3/4",
          "inset-y-0",
          "sm:max-w-sm",
          "flex",
          "flex-col",
          "space-y-2",
          "text-center",
          "sm:text-left",
          "flex-col-reverse",
          "sm:flex-row",
          "sm:justify-end",
          "sm:space-x-2",
          "text-lg",
          "font-semibold",
          "text-foreground",
          "text-sm",
          "text-muted-foreground",
          "absolute",
          "right-4",
          "top-4",
          "rounded-sm",
          "opacity-70",
          "ring-offset-background",
          "hover:opacity-100",
          "focus:outline-none",
          "focus:ring-2",
          "focus:ring-ring",
          "focus:ring-offset-2",
          "disabled:pointer-events-none",
          "bg-transparent",
          "data-[state=open]:bg-secondary",
          "sr-only",
        ],
        // slider:
        ...[
          "relative",
          "flex",
          "w-full",
          "touch-none",
          "select-none",
          "items-center",
          "grow",
          "overflow-hidden",
          "rounded-full",
          "bg-opacity-20",
          "absolute",
          "bg-primary",
          "block",
          "h-4",
          "w-4",
          "border",
          "border-primary/50",
          "bg-background",
          "shadow",
          "transition-colors",
          "focus-visible:outline-none",
          "focus-visible:ring-1",
          "focus-visible:ring-ring",
          "disabled:pointer-events-none",
          "disabled:opacity-50",
        ],
        // switch:
        ...[
          "peer",
          "inline-flex",
          "h-5",
          "w-9",
          "shrink-0",
          "cursor-pointer",
          "items-center",
          "rounded-full",
          "border-2",
          "border-transparent",
          "shadow-sm",
          "transition-colors",
          "focus-visible:outline-none",
          "focus-visible:ring-2",
          "focus-visible:ring-ring",
          "focus-visible:ring-offset-2",
          "focus-visible:ring-offset-background",
          "disabled:cursor-not-allowed",
          "disabled:opacity-50",
          "data-[state=checked]:bg-primary",
          "data-[state=unchecked]:bg-input",
          "pointer-events-none",
          "block",
          "h-4",
          "w-4",
          "bg-background",
          "shadow-lg",
          "ring-0",
          "transition-transform",
          "data-[state=checked]:translate-x-4",
          "data-[state=unchecked]:translate-x-0",
        ],
        // tabs:
        ...[
          "inline-flex",
          "h-9",
          "items-center",
          "justify-center",
          "rounded-lg",
          "bg-muted",
          "p-1",
          "text-muted-foreground",
          "whitespace-nowrap",
          "rounded-md",
          "px-3",
          "py-1",
          "text-sm",
          "font-medium",
          "ring-offset-background",
          "transition-all",
          "focus-visible:outline-none",
          "focus-visible:ring-2",
          "focus-visible:ring-ring",
          "focus-visible:ring-offset-2",
          "disabled:pointer-events-none",
          "disabled:opacity-50",
          "data-[state=active]:bg-background",
          "data-[state=active]:text-foreground",
          "data-[state=active]:shadow",
          "mt-2",
        ],
        // toast:
        ...[
          "fixed",
          "top-0",
          "z-[100]",
          "flex",
          "max-h-screen",
          "w-full",
          "flex-col-reverse",
          "p-4",
          "sm:bottom-0",
          "sm:right-0",
          "sm:top-auto",
          "sm:flex-col",
          "md:max-w-[420px]",
          "group",
          "pointer-events-auto",
          "relative",
          "items-center",
          "justify-between",
          "space-x-2",
          "overflow-hidden",
          "rounded-md",
          "border",
          "p-4",
          "pr-6",
          "shadow-lg",
          "transition-all",
          "data-[swipe=cancel]:translate-x-0",
          "data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)]",
          "data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)]",
          "data-[swipe=move]:transition-none",
          "data-[state=open]:animate-in",
          "data-[state=closed]:animate-out",
          "data-[swipe=end]:animate-out",
          "data-[state=closed]:fade-out-80",
          "data-[state=closed]:slide-out-to-right-full",
          "data-[state=open]:slide-in-from-top-full",
          "data-[state=open]:sm:slide-in-from-bottom-full",
          "toast",
          "variant-default",
          "variant-destructive",
          "group-[.destructive]",
          "group-hover",
          "toast-close",
          "text-red-300",
          "hover:text-red-50",
          "focus:ring-red-400",
          "focus:ring-offset-red-600",
          "text-foreground/50",
          "hover:text-foreground",
          "focus:opacity-100",
          "focus:ring-1",
          "focus:ring-ring",
          "focus:ring-destructive",
          "opacity-0",
          "hover:text-foreground",
          "hover:bg-secondary",
          "focus:outline-none",
          "focus:ring-1",
          "focus:ring-ring",
          "focus:ring-offset-2",
          "disabled:pointer-events-none",
          "disabled:opacity-50",
          "data-[state=active]:bg-background",
          "data-[state=active]:text-foreground",
          "data-[state=active]:shadow",
          "mt-2",
          "sm:text-left",
          "text-lg",
          "font-semibold",
          "[&+div]:text-xs",
          "text-sm",
          "opacity-90",
          "absolute",
          "right-1",
          "top-1",
          "rounded-md",
          "p-1",
          "text-foreground/50",
          "opacity-0",
          "hover:text-foreground",
          "focus:opacity-100",
          "focus:ring-1",
          "group-hover:opacity-100",
          "mdi-close",
          "h-4",
          "w-4",
          "text-xs",
          "sm:flex-row",
          "sm:justify-end",
          "sm:space-x-2",
          "text-red-50",
          "mdi-close",
          "h-4",
          "w-4",
          "mdi-close",
          "h-4",
          "w-4",
        ],
        // tooltip:
        ...[
          "z-50",
          "overflow-hidden",
          "rounded-md",
          "bg-primary",
          "px-3",
          "py-1.5",
          "text-xs",
          "text-primary-foreground",
          "animate-in",
          "fade-in-0",
          "zoom-in-95",
          "data-[state=closed]:animate-out",
          "data-[state=closed]:fade-out-0",
          "data-[state=closed]:zoom-out-95",
          "data-[side=bottom]:slide-in-from-top-2",
          "data-[side=left]:slide-in-from-right-2",
          "data-[side=right]:slide-in-from-left-2",
          "data-[side=top]:slide-in-from-bottom-2",
        ],
      ]),
    ],

    variants: [variantGroupDataAttribute.match],

    rules: [
      [
        "animate-accordion-down",
        {
          animation: "shadcn-down 0.2s ease-out",
        },
      ],
      [
        "animate-accordion-up",
        {
          animation: "shadcn-up 0.2s ease-out",
        },
      ],
      [
        "animate-collapsible-down",
        {
          animation: "shadcn-collapsible-down 0.2s ease-out",
        },
      ],
      [
        "animate-collapsible-up",
        {
          animation: "shadcn-collapsible-up 0.2s ease-out",
        },
      ],
    ],

    theme: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
    },
    // NOTE: build step required for transformers (see @unocss/unocss#1673)
    // transformers: [transformerDirectives(), transformerVariantGroup()],
  };
}

export default presetShadcn;
