// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "fresh/server.ts";
import * as $CheckDuplication from "./islands/CheckDuplication.tsx";
import * as $InsertCssRules from "./islands/InsertCssRules.tsx";
import * as $index from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CheckDuplication.tsx": $CheckDuplication,
    "./islands/InsertCssRules.tsx": $InsertCssRules,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
