// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/auth.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/auth-form.tsx";

const manifest = {
  routes: {
    "./routes/auth.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/user-auth-form.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
