// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_layout.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/[type].ts";
import * as $3 from "./routes/hydro.tsx";
import * as $4 from "./routes/solar.tsx";
import * as $5 from "./routes/wind.tsx";
import * as $$0 from "./islands/Hydro.tsx";
import * as $$1 from "./islands/Solar.tsx";
import * as $$2 from "./islands/Wind.tsx";

const manifest = {
  routes: {
    "./routes/_layout.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/[type].ts": $2,
    "./routes/hydro.tsx": $3,
    "./routes/solar.tsx": $4,
    "./routes/wind.tsx": $5,
  },
  islands: {
    "./islands/Hydro.tsx": $$0,
    "./islands/Solar.tsx": $$1,
    "./islands/Wind.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
