// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[id].tsx'
import * as $1 from './routes/index.tsx'

const manifest = {
  routes: {
    './routes/[id].tsx': $0,
    './routes/index.tsx': $1,
  },
  islands: {},
  baseUrl: import.meta.url,
}

export default manifest
