// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/api/products/[id].ts'
import * as $1 from './routes/api/products/index.ts'
import * as $2 from './routes/api/sales/[id].ts'
import * as $3 from './routes/api/sales/index.ts'
import * as $4 from './routes/index.tsx'
import * as $$0 from './islands/App.tsx'
import * as $$1 from './islands/ModalInspect.tsx'

const manifest = {
  routes: {
    './routes/api/products/[id].ts': $0,
    './routes/api/products/index.ts': $1,
    './routes/api/sales/[id].ts': $2,
    './routes/api/sales/index.ts': $3,
    './routes/index.tsx': $4,
  },
  islands: {
    './islands/App.tsx': $$0,
    './islands/ModalInspect.tsx': $$1,
  },
  baseUrl: import.meta.url,
}

export default manifest
