export const baseImports = {
  "@/": "./",
  "netzo/": "https://deno.land/x/netzo@0.3.45/",
  "$fresh/": "https://deno.land/x/fresh@1.6.1/",
  "preact": "https://esm.sh/v135/preact@10.19.2",
  "preact/": "https://esm.sh/v135/preact@10.19.2/",
  "@preact/signals": "https://esm.sh/v135/*@preact/signals@1.2.1",
  "@preact/signals-core": "https://esm.sh/v135/*@preact/signals-core@1.5.0",
  "std/": "https://deno.land/std@0.205.0/",
  "react": "https://esm.sh/v135/preact@10.19.2/compat",
  "react-dom": "https://esm.sh/v135/preact@10.19.2/compat",
  "react/jsx-runtime": "https://esm.sh/v135/preact@10.19.2/compat",
};

export const imports = {
  "@radix-ui/colors": "netzo/deps/@radix-ui/colors.ts",
  "@radix-ui/react-accordion": "netzo/deps/@radix-ui/react-accordion.ts",
  "@radix-ui/react-alert-dialog": "netzo/deps/@radix-ui/react-alert-dialog.ts",
  "@radix-ui/react-aspect-ratio": "netzo/deps/@radix-ui/react-aspect-ratio.ts",
  "@radix-ui/react-avatar": "netzo/deps/@radix-ui/react-avatar.ts",
  "@radix-ui/react-checkbox": "netzo/deps/@radix-ui/react-checkbox.ts",
  "@radix-ui/react-collapsible": "netzo/deps/@radix-ui/react-collapsible.ts",
  "@radix-ui/react-context-menu": "netzo/deps/@radix-ui/react-context-menu.ts",
  "@radix-ui/react-dialog": "netzo/deps/@radix-ui/react-dialog.ts",
  "@radix-ui/react-dropdown-menu":
    "netzo/deps/@radix-ui/react-dropdown-menu.ts",
  "@radix-ui/react-form": "netzo/deps/@radix-ui/react-form.ts",
  "@radix-ui/react-hover-card": "netzo/deps/@radix-ui/react-hover-card.ts",
  "@radix-ui/react-icons": "netzo/deps/@radix-ui/react-icons.ts",
  "@radix-ui/react-label": "netzo/deps/@radix-ui/react-label.ts",
  "@radix-ui/react-menubar": "netzo/deps/@radix-ui/react-menubar.ts",
  "@radix-ui/react-navigation-menu":
    "netzo/deps/@radix-ui/react-navigation-menu.ts",
  "@radix-ui/react-popover": "netzo/deps/@radix-ui/react-popover.ts",
  "@radix-ui/react-progress": "netzo/deps/@radix-ui/react-progress.ts",
  "@radix-ui/react-radio-group": "netzo/deps/@radix-ui/react-radio-group.ts",
  "@radix-ui/react-scroll-area": "netzo/deps/@radix-ui/react-scroll-area.ts",
  "@radix-ui/react-select": "netzo/deps/@radix-ui/react-select.ts",
  "@radix-ui/react-separator": "netzo/deps/@radix-ui/react-separator.ts",
  "@radix-ui/react-slider": "netzo/deps/@radix-ui/react-slider.ts",
  "@radix-ui/react-slot": "netzo/deps/@radix-ui/react-slot.ts",
  "@radix-ui/react-switch": "netzo/deps/@radix-ui/react-switch.ts",
  "@radix-ui/react-tabs": "netzo/deps/@radix-ui/react-tabs.ts",
  "@radix-ui/react-toast": "netzo/deps/@radix-ui/react-toast.ts",
  "@radix-ui/react-toggle": "netzo/deps/@radix-ui/react-toggle.ts",
  "@radix-ui/react-toggle-group": "netzo/deps/@radix-ui/react-toggle-group.ts",
  "@radix-ui/react-toolbar": "netzo/deps/@radix-ui/react-toolbar.ts",
  "@radix-ui/react-tooltip": "netzo/deps/@radix-ui/react-tooltip.ts",
  "@tanstack/react-table": "netzo/deps/@tanstack/react-table.ts",
  "class-variance-authority": "netzo/deps/class-variance-authority.ts",
  "clsx": "netzo/deps/clsx.ts",
  "cmdk": "netzo/deps/cmdk.ts",
  "date-fns": "netzo/deps/date-fns.ts",
  "lodash.get": "netzo/deps/lodash.get.ts",
  "react-day-picker": "netzo/deps/react-day-picker.ts",
  "react-hook-form": "netzo/deps/react-hook-form.ts",
  "@hookform/resolvers/": "netzo/deps/@hookform/resolvers/zod.ts",
  "tailwind-merge": "netzo/deps/tailwind-merge.ts",
  "zod/": "netzo/deps/zod/",
};
