// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/[locale]/[templateId].tsx'
import * as $1 from './routes/[locale]/index.tsx'
import * as $2 from './routes/_middleware.ts'

const manifest = {
  routes: {
    './routes/[locale]/[templateId].tsx': $0,
    './routes/[locale]/index.tsx': $1,
    './routes/_middleware.ts': $2,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
}

export default manifest
